function HI4802879(){var gb='',db=' top: -1000px;',Db='" for "gwt:onLoadErrorFn"',Bb='" for "gwt:onPropertyErrorFn"',mb='");',Eb='#',Ob='&',rc='.cache.js',Gb='/',Mb='//',ic='2F260D560C9326635ECEA1E13E8491FC',lc='78B6A3C0E3F1784635F087FAE6591FEB',mc='92CF12297DD66C89DC130F3931FA63EB',qc=':',jc=':1',kc=':2',vb='::',zc=':moduleBase',fb='<!doctype html>',hb='<html><head><\/head><body><\/body><\/html>',yb='=',Fb='?',nc='BC7EA00A51725DEA430493307192AF9D',Ab='Bad handler "',oc='CB802C4C151E05F36547AF5C8B75CC4F',eb='CSS1Compat',kb='Chrome',pc='D6667074C74C41369AF17C00FAB59D48',jb='DOMContentLoaded',$='DUMMY',Y='HI4802879',hc='HI4802879.devmode.js',Kb='HI4802879.nocache.js',ub='HI4802879::',yc='Ignoring non-whitelisted Dev Mode URL: ',xc='__gwtDevModeHook:HI4802879',wc='_gwt_dummy_',Tb='android',Lb='base',Jb='baseUrl',V='begin',_='body',U='bootstrap',Ib='clear.cache.gif',xb='content',Wb='desktop',tc='end',lb='eval("',vc='file:',Nb='formfactor',dc='gecko',ec='gecko1_8',W='gwt.codesvr.HI4802879=',X='gwt.codesvr=',Cb='gwt:onLoadErrorFn',zb='gwt:onPropertyErrorFn',wb='gwt:property',rb='head',uc='http:',_b='ie10',cc='ie6',bc='ie8',ac='ie9',ab='iframe',Hb='img',Sb='ipad',Pb='iphone',Qb='ipod',ob='javascript',bb='javascript:""',sc='loadExternalRefs',sb='meta',Ub='mobile',qb='moduleRequested',pb='moduleStartup',$b='msie',tb='name',Rb='phone',cb='position:absolute; width:0; height:0; border:none; left: -1000px;',Zb='safari',nb='script',gc='selectingPermutation',Z='startup',Vb='tablet',ib='undefined',fc='unknown',Xb='user.agent',Yb='webkit';var s=window;var t=document;v(U,V);function u(){var a=s.location.search;return a.indexOf(W)!=-1||a.indexOf(X)!=-1}
function v(a,b){if(s.__gwtStatsEvent){s.__gwtStatsEvent({moduleName:Y,sessionId:s.__gwtStatsSessionId,subSystem:Z,evtGroup:a,millis:(new Date).getTime(),type:b})}}
HI4802879.__sendStats=v;HI4802879.__moduleName=Y;HI4802879.__errFn=null;HI4802879.__moduleBase=$;HI4802879.__softPermutationId=0;HI4802879.__computePropValue=null;HI4802879.__getPropMap=null;HI4802879.__gwtInstallCode=function(){};HI4802879.__gwtStartLoadingFragment=function(){return null};var w=function(){return false};var A=function(){return null};__propertyErrorFunction=null;var B=s.__gwt_activeModules=s.__gwt_activeModules||{};B[Y]={moduleName:Y};var C;function D(){G();return C}
function F(){G();return C.getElementsByTagName(_)[0]}
function G(){if(C){return}var a=t.createElement(ab);a.src=bb;a.id=Y;a.style.cssText=cb+db;a.tabIndex=-1;t.body.appendChild(a);C=a.contentDocument;if(!C){C=a.contentWindow.document}C.open();var b=document.compatMode==eb?fb:gb;C.write(b+hb);C.close()}
function H(k){function l(a){function b(){if(typeof t.readyState==ib){return typeof t.body!=ib&&t.body!=null}return /loaded|complete/.test(t.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(t.removeEventListener){t.removeEventListener(jb,d,false)}if(e){clearInterval(e)}}}
if(t.addEventListener){t.addEventListener(jb,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=F();var f=D();var g;if(navigator.userAgent.indexOf(kb)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(lb));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode(mb));g=f.createElement(nb);g.language=ob;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(nb);g.language=ob;g.text=c[i];e.appendChild(g);d(e,g)}}}
HI4802879.onScriptDownloaded=function(a){l(function(){m(a)})};v(pb,qb);var n=t.createElement(nb);n.src=k;t.getElementsByTagName(rb)[0].appendChild(n)}
HI4802879.__startLoadingFragment=function(a){return K(a)};HI4802879.__installRunAsyncCode=function(a){var b=F();var c=D().createElement(nb);c.language=ob;c.text=a;b.appendChild(c);b.removeChild(c)};function I(){var c={};var d;var e;var f=t.getElementsByTagName(sb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(tb),k;if(j){j=j.replace(ub,gb);if(j.indexOf(vb)>=0){continue}if(j==wb){k=i.getAttribute(xb);if(k){var l,m=k.indexOf(yb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=gb}c[j]=l}}else if(j==zb){k=i.getAttribute(xb);if(k){try{d=eval(k)}catch(a){alert(Ab+k+Bb)}}}else if(j==Cb){k=i.getAttribute(xb);if(k){try{e=eval(k)}catch(a){alert(Ab+k+Db)}}}}}A=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;HI4802879.__errFn=e}
function J(){function e(a){var b=a.lastIndexOf(Eb);if(b==-1){b=a.length}var c=a.indexOf(Fb);if(c==-1){c=a.length}var d=a.lastIndexOf(Gb,Math.min(c,b));return d>=0?a.substring(0,d+1):gb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=t.createElement(Hb);b.src=a+Ib;a=e(b.src)}return a}
function g(){var a=A(Jb);if(a!=null){return a}return gb}
function h(){var a=t.getElementsByTagName(nb);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(Kb)!=-1){return e(a[b].src)}}return gb}
function i(){var a=t.getElementsByTagName(Lb);if(a.length>0){return a[a.length-1].href}return gb}
function j(){var a=t.location;return a.href==a.protocol+Mb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==gb){k=h()}if(k==gb){k=i()}if(k==gb&&j()){k=e(t.location.href)}k=f(k);return k}
function K(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return HI4802879.__moduleBase+a}
function L(){var k=[];var l=0;function m(a,b){var c=k;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var n=[];var o=[];function p(a){var b=o[a](),c=n[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
o[Nb]=function(){var a=location.search;var b=a.indexOf(Nb);if(b>=0){var c=a.substring(b);var d=c.indexOf(yb)+1;var e=c.indexOf(Ob);if(e==-1){e=c.length}return c.substring(d,e)}var f=navigator.userAgent.toLowerCase();if(f.indexOf(Pb)!=-1||f.indexOf(Qb)!=-1){return Rb}if(f.indexOf(Sb)!=-1||(f.indexOf(Tb)!=-1||f.indexOf(Ub)!=-1)){var g=160;var h=s.screen.width/g;var i=s.screen.height/g;var j=Math.sqrt(h*h+i*i);if(j<8){return Rb}else{return Vb}}return Wb};n[Nb]={desktop:0,phone:1,tablet:2};o[Xb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Yb)!=-1}())return Zb;if(function(){return b.indexOf($b)!=-1&&t.documentMode>=10}())return _b;if(function(){return b.indexOf($b)!=-1&&t.documentMode>=9}())return ac;if(function(){return b.indexOf($b)!=-1&&t.documentMode>=8}())return bc;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return cc;if(function(){return b.indexOf(dc)!=-1}())return ec;return fc};n[Xb]={gecko1_8:0,ie10:1,ie6:2,ie8:3,ie9:4,safari:5};w=function(a,b){return b in n[a]};HI4802879.__getPropMap=function(){var a={};for(var b in n){if(n.hasOwnProperty(b)){a[b]=p(b)}}return a};HI4802879.__computePropValue=p;s.__gwt_activeModules[Y].bindings=HI4802879.__getPropMap;v(U,gc);if(u()){return K(hc)}var q;try{m([Wb,cc],ic);m([Rb,cc],ic+jc);m([Vb,cc],ic+kc);m([Wb,_b],lc);m([Rb,_b],lc+jc);m([Vb,_b],lc+kc);m([Wb,bc],mc);m([Rb,bc],mc+jc);m([Vb,bc],mc+kc);m([Wb,Zb],nc);m([Rb,Zb],nc+jc);m([Vb,Zb],nc+kc);m([Wb,ac],oc);m([Rb,ac],oc+jc);m([Vb,ac],oc+kc);m([Wb,ec],pc);m([Rb,ec],pc+jc);m([Vb,ec],pc+kc);q=k[p(Nb)][p(Xb)];var r=q.indexOf(qc);if(r!=-1){l=parseInt(q.substring(r+1),10);q=q.substring(0,r)}}catch(a){}HI4802879.__softPermutationId=l;return K(q+rc)}
function M(){if(!s.__gwt_stylesLoaded){s.__gwt_stylesLoaded={}}v(sc,V);v(sc,tc)}
I();HI4802879.__moduleBase=J();B[Y].moduleBase=HI4802879.__moduleBase;var N=L();if(s){var O=!!(s.location.protocol==uc||s.location.protocol==vc);s.__gwt_activeModules[Y].canRedirect=O;function P(){var b=wc;try{s.sessionStorage.setItem(b,b);s.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(O&&P()){var Q=xc;var R=s.sessionStorage[Q];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(R)){if(R&&(window.console&&console.log)){console.log(yc+R)}R=gb}if(R&&!s[Q]){s[Q]=true;s[Q+zc]=J();var S=t.createElement(nb);S.src=R;var T=t.getElementsByTagName(rb)[0];T.insertBefore(S,T.firstElementChild||T.children[0]);return false}}}M();v(U,tc);H(N);return true}
HI4802879.succeeded=HI4802879();